name: Build and Push Docker Image (Release)

on:
  push:
    branches:
      - release

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image with secrets
        run: |
          docker build \
            --build-arg REACT_APP_RAILWAY_PUBLIC_DOMAIN=${{ secrets.REACT_APP_RAILWAY_PUBLIC_DOMAIN }} \
            --build-arg REACT_APP_WEATHER_API_KEY=${{ secrets.REACT_APP_WEATHER_API_KEY }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/your-planner-fe:release .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/your-planner-fe:release